export const CTR_TOKENS = {
  valid: [
    {
      assetId: 'CA4mP5y33VLKZG4vunS1vY5yS3cLY59XK4Dd9j6XMxSE',
      assetName: 'ca4m_solana_c14194ee',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          CA4MsolanaC14194EE: 6,
        },
      },
      ticker: 'CA4MsolanaC14194EE',
      version: 1,
      pricingAvailable: false,
      info: {},
      displayName: 'BLACKPINK 블랙핑크',
      displayTicker: 'BLACKPINK',
      properName: 'BLACKPINK 블랙핑크',
      properTicker: 'BLACKPINK',
    },
    {
      assetId: 'CA4mP5y33VLKZG4vunS1vY5yS3cLY59XK4Dd9j6XMxSE',
      assetName: 'ca4m_solana_c14194ee',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          CA4MsolanaC14194EE: 6,
        },
      },
      ticker: 'CA4MsolanaC14194EE',
      version: 1,
      pricingAvailable: false,
      info: {},
      displayName: 'BLACKPINK 블랙핑크',
      displayTicker: 'BLACKPINK',
      properName: 'BLACKPINK 블랙핑크',
      properTicker: 'BLACKPINK',
      parents: ['one', 'two', '2iud_solana_d82ebc91'],
    },
    {
      assetId: 'cngnf123-vqaaa-aaaar-qag4q-cai',
      assetName: 'cngnf123_internetcomputer_22bac3bd46fb339e',
      assetType: 'ICP_ICRC',
      baseAssetName: 'internetcomputer',
      displayName: 'ckUSDT',
      displayTicker: 'ckUSDT',
      info: {},
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          CNGN123Finternetcomputer22BAC3BD46FB339E: 6,
          base: 0,
        },
      },
      pricingAvailable: false,
      properName: 'ckUSDT',
      properTicker: 'ckUSDT',
      ticker: 'CNGN123Finternetcomputer22BAC3BD46FB339E',
      version: 0,
    },

    {
      assetId: 'G94GQa8zLLcTuVfFbbsr4ajjnjQDFqqVR75PEBYzpump',
      assetName: 'g94g_solana_9834be2e',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          G94Gsolana9834BE2E: 6,
        },
      },
      ticker: 'G94Gsolana9834BE2E',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'ParisCoin',
      displayTicker: 'PARISCOİN',
      properName: 'ParisCoin',
      properTicker: 'PARISCOİN',
    },
    {
      assetId: 'cngnf-vqaaa-aaaar-qag4q-cai',
      assetName: 'cngnf_internetcomputer_22bac3bd',
      assetType: 'ICP_ICRC',
      baseAssetName: 'internetcomputer',
      displayName: 'ckUSDT',
      displayTicker: 'ckUSDT',
      info: {},
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          CNGNFinternetcomputer22BAC3BD: 6,
          base: 0,
        },
      },
      pricingAvailable: false,
      properName: 'ckUSDT',
      properTicker: 'ckUSDT',
      ticker: 'CNGNFinternetcomputer22BAC3BD',
      version: 0,
    },
    {
      assetId: '51L2QtRYtYP1Wotamx5U5QvpqMKopGy5tywfwCyCpump',
      assetName: '51l2_solana_024f128d',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          '51L2solana024F128D': 6,
        },
      },
      ticker: '51L2solana024F128D',
      version: 1,
      pricingAvailable: false,
      info: {},
      displayName: 'jelly',
      displayTicker: 'ゼリー',
      properName: 'jelly',
      properTicker: 'ゼリー',
    },

    {
      assetId: '0x1985365e9f78359a9b6ad760e32412f4a445e862',
      assetName: 'rep_ethereum_3fdfffd2',
      assetType: 'ETHEREUM_ERC20',
      baseAssetName: 'ethereum',
      lifecycleStatus: 'c',
      parameters: { decimals: 18, units: { base: 0, REPv1: 18, REPethereum3FDFFFD2: 18 } },
      properName: 'Augur (old)',
      properTicker: 'REPv1',
      ticker: 'REPethereum3FDFFFD2',
      version: 3,
      displayName: 'Augur (old)',
      displayTicker: 'REPv1',
      pricingAvailable: false,
    },

    {
      assetId: '0x5da42581f68feaefd912850c1ff64825dd53d87d',
      assetName: 'jft_matic_76df88bd',
      assetType: 'MATIC_ERC20',
      baseAssetName: 'matic',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 100,
        units: {
          base: 0,
          JFTmatic76DF88BD: 100,
        },
      },
      ticker: 'JFTmatic76DF88BD',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'jokem',
      displayTicker: 'JFT',
      properName: 'jokem',
      properTicker: 'JFT',
    },
    {
      assetId: '0xddac9c604ba6bc4acec0fbb485b83f390ecf2f31',
      assetName: 'cyop_ethereum_10d8cd50',
      assetType: 'ETHEREUM_ERC20',
      baseAssetName: 'ethereum',
      info: {},
      lifecycleStatus: 'u',
      parameters: {
        decimals: 9,
        units: {
          base: 0,
          CYOPethereum10D8CD50: 9,
        },
      },
      pricingAvailable: false,
      properName: 'CyOp | Protocol',
      properTicker: 'CyOp',
      ticker: 'CYOPethereum10D8CD50',
      version: 0,
    },
    {
      assetId: '312769',
      assetName: 'usdt_algorand_323d502d',
      assetType: 'ALGORAND_TOKEN',
      baseAssetName: 'algorand',
      info: {},
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          USDTalgorand323D502D: 6,
        },
      },
      pricingAvailable: false,
      properName: 'Tether USDt',
      properTicker: 'USDt',
      ticker: 'USDTalgorand323D502D',
      version: 0,
    },
    {
      assetId: 'EzfgjvkSwthhgHaceR3LnKXUoRkP6NUhfghdaHAj1tUv',
      assetName: 'ezfg_solana_de1ca7e7',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      info: {},
      lifecycleStatus: 'u',
      parameters: {
        decimals: 8,
        units: {
          base: 0,
          EZFGsolanaDE1CA7E7: 8,
        },
      },
      pricingAvailable: false,
      properName: 'FTT (Wormhole)',
      properTicker: 'FTX Token',
      ticker: 'EZFGsolanaDE1CA7E7',
      version: 0,
    },
    {
      assetId: '7zhbkbKpGaUsJW7AD4yyAfGGoy53Xx2H3Ai5BKcwGKHw',
      assetName: '7zhb_solana_3a08e34c',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      info: {},
      lifecycleStatus: 'v',
      parameters: {
        decimals: 0,
        units: {
          base: 0,
          '7ZHBsolana3A08E34C': 0,
        },
      },
      pricingAvailable: false,
      properName: 'nom',
      properTicker: 'NOM',
      ticker: '7ZHBsolana3A08E34C',
      version: 1,
    },
    {
      assetId: '0xc0d4ceb216b3ba9c3701b291766fdcba977cec3a',
      assetName: 'btrfly_ethereum_50d6d874',
      assetType: 'ETHEREUM_ERC20',
      baseAssetName: 'ethereum',
      info: {},
      lifecycleStatus: 'u',
      parameters: {
        decimals: 9,
        units: {
          base: 0,
          BTRFLYethereum50D6D874: 9,
        },
      },
      pricingAvailable: false,
      properName: 'BTRFLY',
      properTicker: 'BTRFLY',
      ticker: 'BTRFLYethereum50D6D874',
      version: 0,
    },
    {
      assetId: '0xf0f9D895aCa5c8678f706FB8216fa22957685A13',
      assetName: '0xf0_ethereum_d653647f',
      assetType: 'ETHEREUM_ERC20',
      baseAssetName: 'ethereum',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 18,
        units: {
          base: 0,
          '0XF0ethereumD653647F': 18,
        },
      },
      pricingAvailable: false,
      properName: 'Cult DAO',
      properTicker: 'CULT',
      ticker: '0XF0ethereumD653647F',
      version: 0,
    },
    {
      assetId: '7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj',
      assetName: '7dhb_solana_c9e04412',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 9,
        units: {
          base: 0,
          '7DHBsolanaC9E04412': 9,
        },
      },
      pricingAvailable: false,
      properName: 'Lido Staked SOL',
      properTicker: 'stSOL',
      ticker: '7DHBsolanaC9E04412',
      version: 3,
    },
    {
      assetId: 'poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk',
      assetName: 'poli_solana_0cc3745c',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'v',
      parameters: {
        decimals: 8,
        units: {
          base: 0,
          POLIsolana0CC3745C: 8,
        },
      },
      pricingAvailable: false,
      properName: 'Star Atlas DAO',
      properTicker: 'POLIS',
      ticker: 'POLIsolana0CC3745C',
      version: 1,
      info: {
        description:
          'Star Atlas DAO (POLIS) is a cryptocurrency launched in 2021and operates on the Solana platform. Star Atlas DAO has a current supply of 360,000,000 with 21,600,000 in circulation. The last known price of Star Atlas DAO is 2.02968577 USD and is up 5.24 over the last 24 hours. It is currently trading on 16 active market(s) with $3,894,296.76 traded over the last 24 hours. More information can be found at https://staratlas.com.',
        reddit: 'https://reddit.com/r/staratlas',
        twitter: 'https://twitter.com/staratlas',
        website: 'https://staratlas.com',
      },
    },
    {
      assetId: 'poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk',
      assetName: 'poli_solana_0cc3745c',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'v',
      parameters: {
        decimals: 8,
        units: {
          base: 0,
          POLIsolana0CC3745C: 8,
        },
      },
      pricingAvailable: false,
      properName: 'Star Atlas DAO',
      properTicker: 'POLIS',
      ticker: 'POLIsolana0CC3745C',
      version: 1,
    },
    {
      assetId: 'BYLotMdQmq579hhP9xDcuCJky9kmMrbp77eoktmm7a5Y',
      assetName: 'bylo_solana_fbb2ec80',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      info: {},
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          BYLOsolanaFBB2EC80: 6,
        },
      },
      pricingAvailable: false,
      properName: "CryptoKnight's Gold",
      properTicker: 'CKG',
      ticker: 'BYLOsolanaFBB2EC80',
      version: 0,
    },
    {
      assetId: '29d222ce763455e3d7a09a665ce554f00ac89d2e99a1a83d267170c64d494e',
      assetName: 'min_cardano_8b1b20b4',
      assetType: 'CARDANO_TOKEN',
      baseAssetName: 'cardano',
      info: {},
      lifecycleStatus: 'v',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          MINcardano8B1B20B4: 6,
        },
        policyId: '29d222ce763455e3d7a09a665ce554f00ac89d2e99a1a83d267170c6',
        hexName: '4d494e',
      },
      pricingAvailable: true,
      properName: 'Minswap',
      properTicker: 'MIN',
      ticker: 'MINcardano8B1B20B4',
      version: 2,
    },
    {
      assetId: 'FHKP2nVc44GM5xHqVnytcNo1M162MfL9BJnrimodpump',
      assetName: 'fhkp_solana_fe1f8308',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          FHKPsolanaFE1F8308: 6,
        },
      },
      properName: 'Lina Bytes',
      properTicker: '🦋',
      ticker: 'FHKPsolanaFE1F8308',
      version: 0,
      pricingAvailable: false,
    },
    {
      assetId: '4YxWme1oKkJRdTcRkbfq4aJNs8dW3o3qS7yafCqapump',
      assetName: '4yxw_solana_434148e0',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          '4YXWsolana434148E0': 6,
        },
      },
      ticker: '4YXWsolana434148E0',
      version: 1,
      pricingAvailable: false,
      info: {},
      displayName: '#omochi',
      displayTicker: '#OMOCHI',
      properName: '#omochi',
      properTicker: '#OMOCHI',
    },
    {
      assetId: '0x288710173f12f677ac38b0c2b764a0fea8108cb5e32059c3dd8f650d65e2cb25::pepe::PEPE',
      assetName: 'pepe_sui_0387c93e',
      assetType: 'SUI_TOKEN',
      baseAssetName: 'sui',
      displayName: 'Pepe on Sui',
      displayTicker: 'PEPE',
      info: {},
      lifecycleStatus: 'u',
      parameters: {
        decimals: 2,
        units: {
          PEPEsui0387C93E: 2,
          base: 0,
        },
      },
      pricingAvailable: false,
      properName: 'Pepe on Sui',
      properTicker: 'PEPE',
      ticker: 'PEPEsui0387C93E',
      version: 0,
    },
    {
      assetId: 'EQBlWgKnh_qbFYTXfKgGAQPxkxFsArDOSr9nlARSzydpNPwA',
      assetName: 'eqblwgkn_ton_15401f19',
      assetType: 'TON_TOKEN',
      baseAssetName: 'ton',
      displayName: 'GOVNO',
      displayTicker: 'GOVNO',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 9,
        units: {
          EQBLWGKNton15401F19: 9,
          base: 0,
        },
      },
      pricingAvailable: false,
      properName: 'GOVNO',
      properTicker: 'GOVNO',
      ticker: 'EQBLWGKNton15401F19',
      version: 0,
    },
    {
      assetId: 'EQD44QL9oawLp3hqLNMRd4HvDK-i4mtm6ZBw2CJ7QOtvSNtf',
      assetName: 'eqd44ql9_ton_315f5878',
      assetType: 'TON_TOKEN',
      baseAssetName: 'ton',
      displayName: 'ALISHER 14.02.25',
      displayTicker: 'ALISHER',
      info: {},
      lifecycleStatus: 'u',
      parameters: {
        decimals: 9,
        units: {
          EQD44QL9ton315F5878: 9,
          base: 0,
        },
      },
      pricingAvailable: false,
      properName: 'ALISHER 14.02.25',
      properTicker: 'ALISHER',
      ticker: 'EQD44QL9ton315F5878',
      version: 0,
    },
    {
      assetId: 'TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8',
      assetName: 'usdc_tronmainnet_a4452102ef122316',
      assetType: 'TRON_TOKEN',
      baseAssetName: 'tronmainnet',
      info: {},
      lifecycleStatus: 'c',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          USDCTRX: 6,
          USDCtronmainnetA4452102EF122316: 6,
        },
      },
      pricingAvailable: false,
      properName: 'USDC',
      properTicker: 'USDC',
      displayName: 'USDC',
      displayTicker: 'USDC',
      ticker: 'USDCtronmainnetA4452102EF122316',
      version: 0,
    },
    {
      assetId: '524C555344000000000000000000000000000000.rMxCKbEDwqr76QuheSUMdEGf4B9xJ8m5De',
      assetName: 'rlusd_ripple_1d81dce2',
      assetType: 'RIPPLE_TOKEN',
      baseAssetName: 'ripple',
      displayName: 'RLUSD',
      displayTicker: 'RLUSD',
      info: {},
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          RLUSDripple1D81DCE2: 6,
          base: 0,
        },
      },
      pricingAvailable: false,
      properName: 'RLUSD',
      properTicker: 'RLUSD',
      ticker: 'RLUSDripple1D81DCE2',
      version: 0,
    },
  ],
  invalid: [
    {
      assetId: '0xec5bd46a5085bdfffcf0e89f1029bb0fb59f9ee0',
      assetName: 'opiumlpf4f_ethereum_dedfae6f',
      assetType: 'ETHEREUM_ERC20',
      baseAssetName: 'ethereum',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 18,
        units: {
          base: 0,
          OPIUMLPF4FethereumDEDFAE6F: 18,
        },
      },
      ticker: 'OPIUMLPF4FethereumDEDFAE6F',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'Opium Weekly Turbo 1INCH Seller',
      displayTicker: 'OPIUM_LP_f4f6',
      properName: 'Opium Weekly Turbo 1INCH Seller',
      properTicker: 'OPIUM_LP_f4f6',
    },
    {
      assetId: 'ED6BkECjawrvctnwBn5CvQqb4913aDLG8YN8AypSRGnM',
      assetName: 'ed6b_solana_3d49bf90',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          ED6Bsolana3D49BF90: 6,
        },
      },
      ticker: 'ED6Bsolana3D49BF90',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'Z̶A̴I̴L̶G̶O̸',
      displayTicker: 'ZAILGO',
      properName: 'Z̶A̴I̴L̶G̶O̸',
      properTicker: 'ZAILGO',
    },
    {
      assetId: '2iUde8di6ZbGuUpVNmLrxBYdsDZV5KUcheNgPY8Rpump',
      assetName: '2iud_solana_d82ebc91',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          '2IUDsolanaD82EBC91': 6,
        },
      },
      ticker: '2IUDsolanaD82EBC91',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'ape²',
      displayTicker: 'ape²',
      properName: 'ape²',
      properTicker: 'ape²',
    },
    {
      assetId: '2iUde8di6ZbGuUpVNmLrxBYdsDZV5KUcheNgPY8Rpump',
      assetName: '2iud_solana_d82ebc91',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          '2IUDsolanaD82EBC91': 6,
        },
      },
      ticker: '2IUDsolanaD82EBC91',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'ape²',
      displayTicker: 'ape²',
      properName: 'ape²',
      properTicker: 'ape²',
      parents: ['_api', 'another'],
    },
    {
      assetId: '9ejnviooQPYtc8Se35oH11hwaayvMs8furfqH6qhpump',
      assetName: '9ejn_solana_014bb104',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          '9EJNsolana014BB104': 6,
        },
      },
      ticker: '9EJNsolana014BB104',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'Recovered Сraft',
      displayTicker: 'CRAFT',
      properName: 'Recovered Сraft',
      properTicker: 'CRAFT',
    },
    {
      assetId: '0x874aba417dfa83f5458e3e133fcd24b89a42c886',
      assetName: 'worldcup_ethereum_f19871f2',
      assetType: 'ETHEREUM_ERC20',
      baseAssetName: 'ethereum',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 9,
        units: {
          base: 0,
          WORLDCUPethereumF19871F2: 9,
        },
      },
      ticker: 'WORLDCUPethereumF19871F2',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName:
        'Qatar Ecuador Senegal Netherlands England IR Iran USA Wales Argentina Saudi Arabia Mexico Poland France Australia Denmark Tunisia Spain Costa Rica Germany Japan Belgium Canada Morocco Croatia Brazil Serbia Switzerland Cameroon Portugal Ghana Uruguay Korea Republic',
      displayTicker: 'WorldCup',
      properName:
        'Qatar Ecuador Senegal Netherlands England IR Iran USA Wales Argentina Saudi Arabia Mexico Poland France Australia Denmark Tunisia Spain Costa Rica Germany Japan Belgium Canada Morocco Croatia Brazil Serbia Switzerland Cameroon Portugal Ghana Uruguay Korea Republic',
      properTicker: 'WorldCup',
    },
    {
      assetId: '8pUR42s8Y9oPxcsVrDBpJzKZw16P6HmT8bE9TDoBMVSh',
      assetName: '8pur_solana_b443785c',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 0,
        units: {
          base: 0,
          '8PURsolanaB443785C': 0,
        },
      },
      ticker: '8PURsolanaB443785C',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: '',
      displayTicker: 'DUST',
      properName: '',
      properTicker: 'DUST',
    },
    {
      assetId: 'Cp4DpDvFX5XFWbFZWQsAnG9ZdQKx2huCTqQxV83Upump',
      assetName: 'cp4d_solana_d5c84873',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 6,
        units: {
          base: 0,
          CP4DsolanaD5C84873: 6,
        },
      },
      ticker: 'CP4DsolanaD5C84873',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'SОLВRАIN.FUN',
      displayTicker: 'SBRAIN',
      properName: 'SОLВRАIN.FUN',
      properTicker: 'SBRAIN',
    },
    {
      assetId: 'd1333653aa3ac24adfa9c6d09c1a2cc8e2b7b86ad334c17f2acb864742696f546f6b656e',
      assetName: 'biotoken_cardano_11acebce',
      assetType: 'CARDANO_TOKEN',
      baseAssetName: 'cardano',
      lifecycleStatus: 'v',
      parameters: {
        decimals: null,
        units: {
          base: 0,
          BIOTOKENcardano11ACEBCE: null,
        },
        policyId: 'd1333653aa3ac24adfa9c6d09c1a2cc8e2b7b86ad334c17f2acb8647',
        hexName: '42696f546f6b656e',
      },
      ticker: 'BIOTOKENcardano11ACEBCE',
      version: 2,
      pricingAvailable: true,
      info: {},
      displayName: 'BioToken',
      displayTicker: 'BIO',
      properName: 'BioToken',
      properTicker: 'BIO',
    },
    {
      assetId: 'GuCMPusdmViCsGqKnTEzDqDHs7nE2tzFxMTucz1VUyqK',
      assetName: 'gucm_solana_2d42745e',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 8,
        units: {
          base: 0,
          GUCMsolana2D42745E: 8,
        },
      },
      ticker: 'GUCMsolana2D42745E',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'orcawall.com (+700 ORСА)',
      displayTicker: 'ORCA',
      properName: 'orcawall.com (+700 ORСА)',
      properTicker: 'ORCA',
    },
    {
      assetId: 'HbbkSmEh5aKWKDsXds1aMzuL7iWuJ4RZsawQ6nCd1ATR',
      assetName: 'hbbk_solana_b310519f',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 0,
        units: {
          base: 0,
          HBBKsolanaB310519F: 0,
        },
      },
      ticker: 'HBBKsolanaB310519F',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'Rауdium аlрhа рrоgrаm',
      displayTicker: 'RAP',
      properName: 'Rауdium аlрhа рrоgrаm',
      properTicker: 'RAP',
    },
    {
      assetId: '8YFuK7HzY6JRoP639nFjqdzsSWgM3eC1gY4vCKNp5Pye',
      assetName: '8yfu_solana_8058039d',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 0,
        units: {
          base: 0,
          '8YFUsolana8058039D': 0,
        },
      },
      ticker: '8YFUsolana8058039D',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'Orсa', // c is strange!
      displayTicker: 'OINV',
      properName: 'Orсa',
      properTicker: 'OINV',
    },
    {
      assetId: '8TgS1Z1H3YM2qer6wQfVgfs1zrrkEhN8jwqZwEkuaoQs',
      assetName: '8tgs_solana_c2bf739b',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 0,
        units: {
          base: 0,
          '8TGSsolanaC2BF739B': 0,
        },
      },
      ticker: '8TGSsolanaC2BF739B',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'Ice King Thug: By DizzyJay',
      displayTicker: '',
      properName: 'Ice King Thug: By DizzyJay',
      properTicker: '',
    },

    {
      assetId: '0x477bc8d23c634c154061869478bce96be6045d12',
      assetName: 'sfund_bsc_aea9e987',
      assetType: 'BSC_BEP20',
      baseAssetName: 'bsc',
      info: {
        reddit: 'https://reddit.com/r/seedifyfund',
        twitter: 'https://twitter.com/seedifyfund',
        website: 'https://launchpad.seedify.fund/',
        description:
          'Seedify is a Blockchain Gaming Incubator and Launchpad founded in February 2021 that aims to redefine the blockchain gaming environment by empowering lives through play-to-earn revenue models by providing the best Launchpad and Incubation platform to gaming projects and, launchings these projects to the community via the IGOs (Initial Gaming Offering). Seedify brings to the community the most exciting Blockchain Games initiatives developed on BSC, Polygon and Solana networks. Most recently, Seedify has been strengthening its incubation side to provide even more robust support to early-stages Blockchain Games and help them achieve their full potential when entering the market via the IGOs.This initiative includes a robust game design, tokenomics and marketing support to the games, ensuring they have everything it takes to entertain and generate good profit for its players.Seedify is strongly backed by major Blockchain Companies like Elrond, Polygon and Chainling (among others), besides many big Venture Capitals that provide the foundation needed for Seedifys growth.Seedifys Ecosystem is based on 5 pillars: Launchpad, Incubator, Partners, VCs, and Influencers $ community. Each of these parts has its own features and comes together to enable Seedify to be one of the best Launchpads and Incubators in the Blockchain Market.',
      },
      lifecycleStatus: 'v',
      parameters: {
        decimals: 18,
        units: {
          base: 0,
          SFUNDbscAEA9E987: 18,
        },
      },
      properName: 'SeedifyFund',
      properTicker: 'SFUND',
      ticker: 'SFUNDbscAEA9E987',
      version: 11,
      icon: 'AAA',
      pricingAvailable: true,
      displayName: 'SeedifyFund',
      displayTicker: 'SFUND',
    },
    {
      assetId: 'foo', // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      assetName: 'poli_solana_0cc3745c',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'v',
      parameters: {
        decimals: 8,
        units: {
          base: 0,
          POLIsolana0CC3745C: 8,
        },
      },
      pricingAvailable: false,
      properName: 'Star Atlas DAO',
      properTicker: 'POLIS',
      ticker: 'POLIsolana0CC3745C',
      version: 1,
    },
    {
      assetId: 'a04ce7a52545e5e33c2867e148898d9e667a69602285f6a1298f9d68',
      assetName: 'a04ce7a525_cardano_82c45865',
      assetType: 'CARDANO_TOKEN',
      baseAssetName: 'cardano',
      lifecycleStatus: 'v',
      parameters: {
        decimals: null,
        units: {
          base: 0,
          A04CE7A525cardano82C45865: null,
        },
        policyId: 'a04ce7a52545e5e33c2867e148898d9e667a69602285f6a1298f9d68',
        hexName: '',
      },
      ticker: 'A04CE7A525cardano82C45865',
      version: 2,
      pricingAvailable: true,
      info: {},
      displayName: 'qADA',
      displayTicker: 'qADA',
      properName: 'qADA',
      properTicker: 'qADA',
    },
    {
      assetId: 'poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk',
      assetName: 'polisolana0cc3745c', // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'v',
      parameters: {
        decimals: 8,
        units: {
          base: 0,
          POLIsolana0CC3745C: 8,
        },
      },
      pricingAvailable: false,
      properName: 'Star Atlas DAO',
      properTicker: 'POLIS',
      ticker: 'POLIsolana0CC3745C',
      version: 1,
    },
    {
      assetId: 'poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk',
      assetName: 'poli_solana_0cc3745c',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'asd', // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      parameters: {
        decimals: 8,
        units: {
          base: 0,
          POLIsolana0CC3745C: 8,
        },
      },
      pricingAvailable: false,
      properName: 'Star Atlas DAO',
      properTicker: 'POLIS',
      ticker: 'POLIsolana0CC3745C',
      version: 1,
    },
    {
      assetId: 'poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk',
      assetName: 'poli_solana_0cc3745c',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'v',
      parameters: {
        decimals: 8,
        units: {
          base: 0,
          POLIsolana0CC3745C: 8,
        },
      },
      pricingAvailable: false,
      properName: 'Star Atlas DAO',
      properTicker: 'POLIS',
      ticker: 'POLIsolana0CC3745C',
      version: 1,
      info: {
        description:
          'Star Atlas DAO (POLIS) is a cryptocurrency launched in 2021and operates on the Solana platform. Star Atlas DAO has a current supply of 360,000,000 with 21,600,000 in circulation. The last known price of Star Atlas DAO is 2.02968577 USD and is up 5.24 over the last 24 hours. It is currently trading on 16 active market(s) with $3,894,296.76 traded over the last 24 hours. More information can be found at https://staratlas.com.',
        reddit: 'foo', // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        twitter: 'https://twitter.com/staratlas',
        website: 'https://staratlas.com',
      },
    },
    {
      assetId: 'poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk',
      assetName: 'poli_solana_0cc3745c',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'v',
      parameters: {
        decimals: 300, // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        units: {
          base: 0,
          POLIsolana0CC3745C: 8,
        },
      },
      pricingAvailable: false,
      properName: 'Star Atlas DAO',
      properTicker: 'POLIS',
      ticker: 'POLIsolana0CC3745C',
      version: 1,
      info: {
        description:
          'Star Atlas DAO (POLIS) is a cryptocurrency launched in 2021and operates on the Solana platform. Star Atlas DAO has a current supply of 360,000,000 with 21,600,000 in circulation. The last known price of Star Atlas DAO is 2.02968577 USD and is up 5.24 over the last 24 hours. It is currently trading on 16 active market(s) with $3,894,296.76 traded over the last 24 hours. More information can be found at https://staratlas.com.',
        reddit: 'https://reddit.com/r/staratlas',
        twitter: 'https://twitter.com/staratlas',
        website: 'https://staratlas.com',
      },
    },
    {
      assetId: 'poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk',
      assetName: 'poli_solana_0cc3745c',
      assetType: 'SOLANA_TOKEN',
      // baseAssetName: 'solana', <<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      lifecycleStatus: 'v',
      parameters: {
        decimals: 8,
        units: {
          base: 0,
          POLIsolana0CC3745C: 8,
        },
      },
      pricingAvailable: false,
      properName: 'Star Atlas DAO',
      properTicker: 'POLIS',
      ticker: 'POLIsolana0CC3745C',
      version: 1,
      info: {
        description:
          'Star Atlas DAO (POLIS) is a cryptocurrency launched in 2021and operates on the Solana platform. Star Atlas DAO has a current supply of 360,000,000 with 21,600,000 in circulation. The last known price of Star Atlas DAO is 2.02968577 USD and is up 5.24 over the last 24 hours. It is currently trading on 16 active market(s) with $3,894,296.76 traded over the last 24 hours. More information can be found at https://staratlas.com.',
        reddit: 'https://reddit.com/r/staratlas',
        twitter: 'https://twitter.com/staratlas',
        website: 'https://staratlas.com',
      },
    },
    {
      assetId: 'poLisWXnNRwC6oBu1vHiuKQzFjGL4XDSu4g9qjz9qVk',
      assetName: 'poli_solana_0cc3745c',
      assetType: 'SOLANA_TOKEN',
      baseAssetName: 'solana',
      lifecycleStatus: 'v',
      parameters: {
        decimals: 8,
        units: {
          base: 0,
          POLIsolana0CC3745CCC: 8, // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        },
      },
      pricingAvailable: false,
      properName: 'Star Atlas DAO',
      properTicker: 'POLIS',
      ticker: 'POLIsolana0CC3745C',
      version: 1,
      info: {
        description:
          'Star Atlas DAO (POLIS) is a cryptocurrency launched in 2021and operates on the Solana platform. Star Atlas DAO has a current supply of 360,000,000 with 21,600,000 in circulation. The last known price of Star Atlas DAO is 2.02968577 USD and is up 5.24 over the last 24 hours. It is currently trading on 16 active market(s) with $3,894,296.76 traded over the last 24 hours. More information can be found at https://staratlas.com.',
        reddit: 'https://reddit.com/r/staratlas',
        twitter: 'https://twitter.com/staratlas',
        website: 'https://staratlas.com',
      },
    },
    {
      assetId: '0x92469391cdec250798551ad3cb7c4314f9cc9e8e',
      assetName: 'bonkbonkbo_bsc_f923fa4b',
      assetType: 'BSC_BEP20',
      baseAssetName: 'bsc',
      lifecycleStatus: 'u',
      parameters: {
        decimals: 9,
        units: {
          base: 0,
          BONKBONKBObscF923FA4B: 9,
        },
      },
      ticker: 'BONKBONKBObscF923FA4B',
      version: 0,
      pricingAvailable: false,
      info: {},
      displayName: 'BonkBonk',
      displayTicker:
        'BonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonk',
      properName: 'BonkBonk',
      properTicker:
        'BonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonkBonk',
    },
  ],
  formerBuiltIn: [
    {
      assetId: '0xc748673057861a797275cd8a068abb95a902e8de',
      assetName: 'babydoge_bsc_ee74eb55',
      assetType: 'BSC_BEP20',
      baseAssetName: 'bsc',
      lifecycleStatus: 'c',
      parameters: {
        decimals: 9,
        units: {
          base: 0,
          BABYDOGEBSC: 9,
          BABYDOGEbscEE74EB55: 9,
        },
      },
      pricingAvailable: false,
      properName: 'BABY DOGE',
      properTicker: 'BABYDOGE',
      ticker: 'BABYDOGEbscEE74EB55',
      version: 11,
    },
  ],
}
